export const eventConstants = {
    EVENTS_FETCHED: 'EVENTS_FETCHED',
    EVENT_FETCH_FAIL: 'EVENTS_FETCH_FAIL',
    
    EVENT_ADDED: 'EVENT_ADDED',
    EVENT_ADD_FAIL: 'EVENT_ADD_FAIL',

    EVENT_EDITED: 'EVENT_EDITED',
    EVENT_EDIT_FAIL: 'EVENT_EDIT_FAIL',

    EVENT_DELETED: 'EVENT_DELETED',
    EVENT_DELETE_FAIL: 'EVENT_DELETE_FAIL',

    SINGLE_EVENT_FETCHED: 'SINGLE_EVENT_FETCHED',
    SINGLE_EVENT_FETCH_FAIL: 'SINGLE_EVENT_FETCH_FAIL'
}