export const eventConstants = {
    EVENTS_FETCHED: 'EVENTS_FETCHED',
    EVENT_FETCH_FAIL: 'EVENTS_FETCH_FAIL',

    MONTHLY_EVENTS_FETCHED: 'MONTHLY_EVENTS_FETCHED',
    MONTHLY_EVENTS_FAIL: 'MONTHLY_EVENTS_FAIL',

    WEEKLY_EVENTS_FETCHED: 'WEEKLY_EVENTS_FETCHED',
    WEEKLY_EVENTS_FAIL: 'WEEKLY_EVENTS_FAIL',

    DAILY_EVENTS_FETCHED: 'DAILY_EVENTS_FETCHED',
    DAILY_EVENTS_FAIL: 'DAILY_EVENTS_FAIL',
    
    EVENT_ADDED: 'EVENT_ADDED',
    EVENT_ADD_FAIL: 'EVENT_ADD_FAIL',

    EVENT_EDITED: 'EVENT_EDITED',
    EVENT_EDIT_FAIL: 'EVENT_EDIT_FAIL',

    EVENT_DELETED: 'EVENT_DELETED',
    EVENT_DELETE_FAIL: 'EVENT_DELETE_FAIL',

    SINGLE_EVENT_REQUEST: 'SINGLE_EVENT_REQUEST',
    SINGLE_EVENT_FETCHED: 'SINGLE_EVENT_FETCHED',
    SINGLE_EVENT_FETCH_FAIL: 'SINGLE_EVENT_FETCH_FAIL'
}